# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

description: >- # this means to ignore newlines until "baseurl:"
  This is the place where I collect and share all the knowledge I have learned and gained over the period of time.
  This blog is mainily focused on capturing the technical learning. 
baseurl: "" # the subpath of your site, e.g. /blog
url: https://kuros.in

# Site Settings
locale                   : "en-US"
title                    : "Kuros.in"
title_separator          : "-"
subtitle                 : "A collection of things I learn and try, simplified."
logo                     : "/images/logo/logo-dark.svg"
icon                     : "/images/kuros-3.png"
repository               : kuros/kuros.github.io
minimal_mistakes_skin    : default # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

search                   : true # true, false (default)
search_full_content      : true # true, false (default)
search_provider          : lunr # lunr (default), algolia
environment              : prod

comments:
  provider               : "discus" # false (default), "disqus", "discourse", "facebook", "staticman_v2", "staticman", "utterances", "custom"
  disqus:
    shortname            : kuros-in

after_footer_scripts:
  - /assets/js/custom.js

# Site Author
author:
  name             : Kumar Rohit
  avatar           : "/images/about/myphoto.png"
  bio              : "I like long drives, bike trip & good food. I have passion for coding, especially for Clean-Code."
  location         : "India"
  links:
    # - label: "Made Mistakes"
    #   icon: "fas fa-fw fa-link"
    #   url: "https://mademistakes.com"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/incrv"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/kuros"
    # - label: "Instagram"
    #   icon: "fab fa-fw fa-instagram"
    #   url: "https://instagram.com/mmistakes"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/incrv"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/kuros"


encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

sidebar_sticky: false
# Ad settings
ads:
  sidebar: true



# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # https://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Outputting
# permalink: /:categories/:title/
permalink: /:categories/:year/:month/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/


category_archive:
  type: jekyll-archives
  path: /categories/
tag_archive:
  type: jekyll-archives
  path: /tags/
jekyll-archives:
  enabled:
    - categories
    - tags
  layouts:
    category: archive-taxonomy
    tag: archive-taxonomy
  permalinks:
    category: /categories/:name/
    tag: /tags/:name/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-archives


# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-archives

# HTML Compression
# - https://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: # true
      share: true
      related: true
  - scope:
      path: ""
      type: tag
    values:
      author_profile: true
  - scope:
      path: ""
      type: category
    values:
      author_profile: true